// reactjs/src/App.js
import React, {Component} from 'react';
import Data from './generate';

class App extends Component {
    constructor() {
        super();

        this.state = {
            data: [],
            generateStart: null,
            generateEnd: null,
            testData: JSON.parse(localStorage.getItem('test:react') || '[]'),
            loadStart: window['loadStart'],
            loadEnd: null,
            iteration: parseInt(localStorage.getItem('iteration:react'), 10) || 0
        }
    }

    componentWillReceiveProps(state, data) {
        console.log(state);
        console.log(data);
    }

    generate() {
        let data = new Data().generate();
        this.setState({
            generateStart: new Date().getTime(),
            data: data
        });

        setTimeout(() => {
            this.setState({
                generateEnd: new Date().getTime()
            });

            const newData = [...this.state.testData, {
                loadTime: window['loadEnd'] - window['loadStart'],
                generationTime: this.state.generateEnd - this.state.generateStart,
                iteration: this.state.iteration
            }];


            this.setState({testData: newData});

            setTimeout(() => {
                this.regenerate();
            }, 3000);
        }, 0);
    };

    regenerate = () => {
        let data = new Data().generate();
        this.setState({
            generateStart: new Date().getTime(),
            data: data
        });

        setTimeout(() => {
            this.setState({
                generateEnd: new Date().getTime()
            });

            this.state.testData[this.state.iteration].regenerate = this.state.generateEnd - this.state.generateStart;
            this.setState({
                iteration: ++this.state.iteration
            });
            localStorage.setItem('iteration:react', this.state.iteration);
            localStorage.setItem('test:react', JSON.stringify(this.state.testData));

            if (!window['stopMeasure']) {
                setTimeout(() => {
                    window.location.reload();
                }, 5000);
            }

        }, 0);

    };

    render() {
        return (
            <div className="container">
                <table className="table table-striped" id="generated">
                    <thead>
                    <tr>
                        <th>No.</th>
                        <th>Adjective</th>
                        <th>Color</th>
                        <th>Thing</th>
                    </tr>
                    </thead>
                    <tbody>
                    {this.state.data.map(object => {
                        return (
                            <tr key={object.id}>
                                <td>{object.id}</td>
                                <td>{object.adjective}</td>
                                <td>{object.color}</td>
                                <td>{object.thing}</td>
                            </tr>
                        );
                    })}

                    </tbody>
                </table>
            </div>
        );
    }

    componentDidMount() {
        this.setState({
            loadEnd: new Date().getTime()
        });
        window['loadEnd'] = new Date().getTime();
        setTimeout(() => {
            this.generate();
        }, 200);
    }
}

export default App;

// angular/src/app/app.component.ts
import {Component} from '@angular/core';
import {Data} from '../generate';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})

export class AppComponent {

  constructor() {
  }

  data = [];
  generateStart = null;
  generateEnd = null;
  testData = [];
  loadStart = null;
  loadEnd = null;
  iteration = 0;

  generate = () => {
    this.generateStart = new Date().getTime();
    this.data = new Data().generate();

    setTimeout(() => {
      this.generateEnd = new Date().getTime();


      this.testData.push({
        loadTime: this.loadEnd - this.loadStart,
        generationTime: this.generateEnd - this.generateStart,
        iteration: this.iteration
      });

      setTimeout(() => {
        this.regenerate();
      }, 3000);
    }, 0);
  };

  regenerate = () => {
    let data = new Data().generate();
    this.generateStart = new Date().getTime();
    this.data = data;

    setTimeout(() => {
      this.generateEnd = new Date().getTime();

      this.testData[this.iteration].regenerate = this.generateEnd - this.generateStart;
      this.iteration++;
      localStorage.setItem('iteration:angular', this.iteration.toString());
      localStorage.setItem('test:angular', JSON.stringify(this.testData));

      if (!window['stopMeasure']) {
        setTimeout(() => {
          window.location.reload();
        }, 5000);
      }
    }, 0);

  };

  ngOnInit() {
    this.iteration = parseInt(localStorage.getItem('iteration:angular'), 10) || 0;
    this.testData = JSON.parse(localStorage.getItem('test:angular') || '[]');
    this.loadEnd = new Date().getTime();
    this.loadStart = window['loadStart'];
    window['stopMeasure'] = false;

    setTimeout(() => {
      this.generate();
    }, 500);
  }


}

<div class="container theme-showcase" role="main">

  <!-- Main jumbotron for a primary marketing message or call to action -->
  <div class="jumbotron">
    <h1>Angular 5 test</h1>
    <p>This test will run after 1 second:</p>
    <p>
      <button type="button" class="btn btn-sm btn-alert" onclick="stopTest();">Stop</button>
    </p>
    <p>
      <button type="button" class="btn btn-sm btn-primary" onclick="showResults();">Results</button>
    </p>
  </div>

  <table class="table table-striped" id="generated" >
    <thead>
    <th>No.</th>
    <th>Adjective</th>
    <th>Color</th>
    <th>Thing</th>
    </thead>
    <tbody>
    <tr *ngFor="let item of data">
      <td> {{item.id}}</td>
      <td> {{item.adjective}}</td>
      <td> {{item.color}}</td>
      <td> {{item.thing}}</td>
    </tr>
    </tbody>
  </table>
</div>
